=pod

=head1 DESCRIPTION

This class and its subclasses define the objects that can be returned from
GuildWars2::API. Some objects also have methods attached to them.

=head1 SUBCLASSES

See the individual modules for documentation of these subclasses.

=item * GuildWars2::API::Objects::Color
=item * GuildWars2::API::Objects::Guild
=item * GuildWars2::API::Objects::Item
=item * GuildWars2::API::Objects::Map
=item * GuildWars2::API::Objects::Recipe

This module defines a role for use by multiple object types.

=item * GuildWars2::API::Objects::Linkable

=cut
