=pod

=head1 DESCRIPTION

This subclass of GuildWars2::API::Objects defines the Guild and Guild::Emblem
objects.


=head1 CLASSES

=head2 Guild

The Guild object represents a guild in Guild Wars 2. It is returned by the $api-
>get_guild() method.

=head3 Attributes

=over

=item guild_id

The internal ID for the guild. Consists of a string of hexadecimal characters in
the pattern XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX.

=item guild_name

The guild's name. Encoded as UTF8.

=item tag

The guild's tag. Encoded as UTF8, max of 4 characters.

=item emblem

A L</"Guild::Emblem"> object.

=back


=head2 Guild::Emblem

The Guild::Emblem object contains information for generating a guild's emblem.

=head3 Attributes

=over

=item background_id
=item foreground_id

The internal ID numbers of the textures used as the emblem background and foreground.

=item flip_background_horizontal
=item flip_background_vertical
=item flip_foreground_horizontal
=item flip_foreground_vertical

Boolean flags that indicate whether the background or foreground should be
flipped and in which direction(s).

=item background_color_id
=item foreground_primary_color_id
=item foreground_secondary_color_id

The internal ID numbers of the colors used in the guild emblem.

=back

=head3 Methods

=over

=item $emblem->generate( $colors, $emblem_texture_folder )

Generates the guild emblem and returns it as an L<Image::Magick> object, which
can then be writte in the image format of your choice.

The arguments must be a L<\"Colors"> object and a path to the local repository
of emblem base textures. In the example below, C<C:/path/to/emblem_textures>
contains the subfolders C<guild emblems> and C<guild emblem backgrounds>.

 my $guild = $api->get_guild("My Guild Name");

 my %colors = $api->get_colors();

 my $emblem = $guild->emblem->generate(\%colors, "C:/path/to/emblem_textures");

 $emblem->Write(filename=>"C:/path/to/generated_emblems/" . $guild->id . ".png");

=back

=cut
